[package]
name = "raytracing"
version = "0.1.0"
authors = ["Samuel Berkun <sberkun@berkeley.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"